
    create sequence account_sequence start with 1 increment by 1;

    create sequence reaction_seq start with 1 increment by 50;

    create table bot (
        id bigint not null,
        owner_id bigint not null,
        registration_date timestamp(6) not null,
        login varchar(20) not null,
        token varchar(255) not null,
        primary key (id)
    );

    create table bot_features (
        bot_id bigint not null,
        features varchar(255)
    );

    create table channel (
        required_access_level integer check (required_access_level>=0),
        id bigint generated by default as identity,
        server_id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table emoji (
        id bigint generated by default as identity,
        server_id bigint not null,
        name varchar(32) not null,
        image_data varbinary(255) not null,
        primary key (id)
    );

    create table membership (
        id bigint generated by default as identity,
        join_date timestamp(6) not null,
        leave_date timestamp(6),
        member_id bigint not null,
        role_id bigint,
        server_id bigint not null,
        primary key (id),
        unique (member_id, server_id, join_date)
    );

    create table message (
        author_id bigint not null,
        channel_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        contents varchar(2000) not null,
        primary key (id)
    );

    create table participation (
        event_id bigint not null,
        id bigint generated by default as identity,
        participant_id bigint not null,
        sign_date timestamp(6) not null,
        primary key (id),
        unique (participant_id, event_id, sign_date)
    );

    create table reaction (
        created_at timestamp(6) not null,
        emoji_id bigint not null,
        id bigint not null,
        message_id bigint not null,
        user_id bigint,
        primary key (id)
    );

    create table role (
        access_level integer check (access_level>=0),
        id bigint generated by default as identity,
        server_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table server (
        id bigint generated by default as identity,
        owner_id bigint not null,
        name varchar(64) not null,
        primary key (id)
    );

    create table server_event (
        end_time timestamp(6) not null,
        id bigint generated by default as identity,
        server_id bigint not null,
        start_time timestamp(6) not null,
        name varchar(64) not null,
        description varchar(500),
        status enum ('CANCELLED','COMPLETED','ONGOING','SCHEDULED'),
        primary key (id),
        unique (name, server_id, start_time, end_time)
    );

    create table subscription (
        end_date timestamp(6),
        id bigint generated by default as identity,
        start_date timestamp(6) not null,
        user_id bigint not null,
        level enum ('CLASSIC','NONE','PRO') not null,
        primary key (id),
        unique (user_id, start_date)
    );

    create table text_channel (
        slowmode integer not null check (slowmode>=0),
        id bigint not null,
        primary key (id)
    );

    create table users (
        id bigint not null,
        registration_date timestamp(6) not null,
        login varchar(20) not null,
        password varchar(64) not null,
        email varchar(255) not null unique,
        primary key (id)
    );

    create table voice_channel (
        bitrate integer not null check ((bitrate<=96) and (bitrate>=8)),
        max_users integer not null check (max_users>=1),
        id bigint not null,
        primary key (id)
    );

    alter table if exists bot 
       add constraint FK7ob66smf69y776n8y9ds2yaxs 
       foreign key (owner_id) 
       references users;

    alter table if exists bot_features 
       add constraint FK3tg1y539bf1q7dd30ajeadn6u 
       foreign key (bot_id) 
       references bot;

    alter table if exists channel 
       add constraint FKb7673tdav6pm22kmr1yr05u7w 
       foreign key (server_id) 
       references server;

    alter table if exists emoji 
       add constraint FK1ghy4v8ccoxxex4rgcai5dewj 
       foreign key (server_id) 
       references server;

    alter table if exists membership 
       add constraint FK53w0pjjpc5me9htly7j74ym1s 
       foreign key (role_id) 
       references role;

    alter table if exists membership 
       add constraint FK5kh1n5q36jcx8ld26850m9h5q 
       foreign key (server_id) 
       references server;

    alter table if exists message 
       add constraint FKlqr4fixlintqc9di9s3u665r4 
       foreign key (author_id) 
       references users;

    alter table if exists message 
       add constraint FKiimr93ytmcuira5le0sldvvma 
       foreign key (channel_id) 
       references channel;

    alter table if exists participation 
       add constraint FKjgvi1hvmka4ffp90ag0iomcn1 
       foreign key (event_id) 
       references server_event;

    alter table if exists participation 
       add constraint FK5d6jm2avy1cbw65o3fqy4twde 
       foreign key (participant_id) 
       references users;

    alter table if exists reaction 
       add constraint FKd7nuihnb8r92l5maihtqxc4dl 
       foreign key (emoji_id) 
       references emoji;

    alter table if exists reaction 
       add constraint FKnnwfsi01kkhg9o9woxilp9dep 
       foreign key (message_id) 
       references message;

    alter table if exists reaction 
       add constraint FK52m11aguxqx0uje12knj056jw 
       foreign key (user_id) 
       references users;

    alter table if exists role 
       add constraint FK4kil0v5bsmbhmu0fqngecat80 
       foreign key (server_id) 
       references server;

    alter table if exists server 
       add constraint FKidd5bkt7d6bqnkdg1v795sihv 
       foreign key (owner_id) 
       references users;

    alter table if exists server_event 
       add constraint FK73t7m1tmxtmsr6ye3mmbgmfwm 
       foreign key (server_id) 
       references server;

    alter table if exists subscription 
       add constraint FKqwd9pkhbsmapx9poug5wnnpkc 
       foreign key (user_id) 
       references users;

    alter table if exists text_channel 
       add constraint FK4puc02fa0h78gs17jfhokj9ml 
       foreign key (id) 
       references channel;

    alter table if exists voice_channel 
       add constraint FKs95ldll8vap7meisoy7lifj5n 
       foreign key (id) 
       references channel;
